[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
exclude = [".ruff_cache", "ui_.*\\.py$"]
fixable = ["ALL"]
ignore = []
select = ["F", "B", "I", "E", "W", "ANN", "TC"]

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
exclude = [
    "ui_.*\\.py$"
]

[mypy-PySide6.*]
ignore_missing_imports = false